**NUMPY Basics**

In [2]:
%%time
marks = [78, 47, 97, 55, 34]
for i in range(len(marks)):
    marks[i]+5
print(marks)

[78, 47, 97, 55, 34]
CPU times: total: 0 ns
Wall time: 988 µs


In [38]:
%%time
item_list = ['Bread', 'Milk', 'Eggs', 'Butter', 'Cocoa']
marks = [78, 47, 96, 55, 34]
hetero_list =  [ 1,2,3.0, 'text', True, 3+2j ]


CPU times: total: 0 ns
Wall time: 0 ns


In [5]:
%%time
#making list without numpy
list1 = list(range(1,1000000))
list2 = list(range(2,1000001))
list3 = []
for i in range(len(list1)):
    list3.append(list1[i]+list2[i])


CPU times: total: 188 ms
Wall time: 179 ms


In [88]:
%%time
#making list using numpy
import numpy as np
a = np.arange(1,1000000)
b = np.arange(2,1000001)
c = a+b

CPU times: total: 15.6 ms
Wall time: 6.58 ms


In [87]:
%%time
#making list using numpy
import numpy as np
a = np.arange(1,10)
b = np.arange(2,11)
print(a)
print(b)
c = a+b
print(c)

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[ 3  5  7  9 11 13 15 17 19]
CPU times: total: 0 ns
Wall time: 996 µs


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
#creating array using numpy
import numpy as np
marks_arr = np.array([1,3,4,6])
marks_arr


array([1, 3, 4, 6])

In [40]:
#import the list in a numpy array
Numbers = [130, 165, 150, 150, 140]
numbers_array = np.array(Numbers)
numbers_array


array([130, 165, 150, 150, 140])

**2D ARRAY**

In [140]:
onebyone = np.array([1])#1X1
print(onebyone, onebyone.shape)

onebytwo = np.array([1,2]) #1X2
print(onebytwo, onebytwo.shape)

onebythree = np.array([1,2,3]) #1X3
print(onebythree, onebythree.shape)

print("\n \n \n")


twobyone = np.array([[1], [2]]) #2X1
print(twobyone, twobyone.shape)

twobytwo = np.array([[1, 2], [3, 4]]) #2X2
print(twobytwo, twobytwo.shape)

twobythree = np.array([[1, 2, 3], [4, 5, 6]]) #2X3
print(twobythree, twobythree.shape)

print("\n \n \n")

threebyone = np.array([[1], [2], [3]]) #3X1
print(threebyone, threebyone .shape)

threebytwo = np.array([[1, 2], [3, 4], [5,6]]) #3X2
print(threebytwo, threebytwo.shape)

threebythree = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]]) #3X3
print(threebythree, threebythree.shape)


[1] (1,)
[1 2] (2,)
[1 2 3] (3,)

 
 

[[1]
 [2]] (2, 1)
[[1 2]
 [3 4]] (2, 2)
[[1 2 3]
 [4 5 6]] (2, 3)

 
 

[[1]
 [2]
 [3]] (3, 1)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [41]:
import numpy as np
#making 2D array
two_dimen = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
two_dimen_array = np.array(two_dimen)
print(two_dimen_array)

#will show the shape of 2D array
print(two_dimen_array.shape)

#will show the data type of the array
print(two_dimen_array.dtype)

two_dimen_array = np.array(two_dimen, dtype = 'float') #making the array float
print(two_dimen_array)
print(two_dimen_array.dtype)

[[ 18  15  18  16  17]
 [130 165 150 150 140]
 [307 350 318 304 302]]
(3, 5)
int32
[[ 18.  15.  18.  16.  17.]
 [130. 165. 150. 150. 140.]
 [307. 350. 318. 304. 302.]]
float64


In [42]:
#Accessing element from 1D array.
fruits = np.array(['Strawberry', 'Mango', 'Lichi', 'Grapes', 'Watermelon'])
fruits[1]


'Mango'

In [45]:
#Accessing element from 2D array.
fruits = np.array(['Strawberry', 'Mango', 'Lichi', 'Grapes', 'Watermelon'])
price = [130, 165, 150, 150, 140]

#importing two list into a 2D array
fruits_price_array = np.array([fruits, price])
print(fruits_price_array)

#accesing a row
print(fruits_price_array[0], "\n")

#accesing a single cell
print(fruits_price_array[0,1])

[['Strawberry' 'Mango' 'Lichi' 'Grapes' 'Watermelon']
 ['130' '165' '150' '150' '140']]
['Strawberry' 'Mango' 'Lichi' 'Grapes' 'Watermelon'] 

Mango


In [46]:
#1d arrray slicing

price = [130, 165, 150, 150, 140]
print(price[1:3])

[165, 150]


In [47]:
#2D arrray slicing
fruits = np.array(['Strawberry', 'Mango', 'Lichi', 'Grapes', 'Watermelon'])
price = [130, 165, 150, 150, 140]
numbers = [18, 15, 18, 16, 17]

fruits_price_numbers = np.array([fruits, price,numbers])
print(fruits_price_numbers, "\n \n")

print(fruits_price_numbers[1:3, 1:3]) #[row, colum]



[['Strawberry' 'Mango' 'Lichi' 'Grapes' 'Watermelon']
 ['130' '165' '150' '150' '140']
 ['18' '15' '18' '16' '17']] 
 

[['165' '150']
 ['15' '18']]


In [50]:
#mean , median , max, min, argmin, argmax
num= np.array( [130, 165, 150, 190, 140])
print("Mean = ",np.mean(num))
print("Median = ",np.median(num))
print("Min = ",np.min(num))
print("Max = ",np.max(num))
print("Index of Minimum : ", np.argmin(num))
print("Index of Maximum : ", np.argmax(num))

Mean =  155.0
Median =  150.0
Min =  130
Max =  190
Index of Minimum :  0
Index of Maximum :  3


In [51]:
#where - filter data
num= np.array( [130, 165, 150, 190, 140])
x = np.where(num > 130)
print(x)
num[x]

(array([1, 2, 3, 4], dtype=int64),)


array([165, 150, 190, 140])

In [53]:
#sorting
num= np.array( [130, 165, 150, 190, 140])
print('original array: ', num)
print('Sorted array: ', np.sort(num)) #temporary sort
print('original array after sorting: ', num)
num.sort() #permanent sort
print('array.sort() :  ', num)

original array:  [130 165 150 190 140]
Sorted array:  [130 140 150 165 190]
original array after sorting:  [130 165 150 190 140]
array.sort() :   [130 140 150 165 190]


In [56]:
#Vectorized operations

marks= np.array([78, 92, 36, 64, 89])
print(np.sum(marks)) #sum of all elements (1D array)

aditional = [2,3,4,5,6]
marks+=aditional #sum of array and list
print(marks)

marks = np.add(marks,aditional) #2D array
print(marks)



359
[80 95 40 69 95]
[ 82  98  44  74 101]


In [74]:
#operations for 2D array

a = np.array([5,6,7,8])
b = np.array([1,2,3,4])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.negative(a))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.floor_divide(a,b))
print(np.power(a,b))
print(np.mod(a,b))



[ 6  8 10 12]
[4 4 4 4]
[-5 -6 -7 -8]
[ 5 12 21 32]
[5.         3.         2.33333333 2.        ]
[5 3 2 2]
[   5   36  343 4096]
[0 0 1 0]


In [108]:
#Broadcasting

import numpy as np
# Array 1
array1=np.array([5, 10, 15])
# Array 2
array2=np.array([5])
print(np.add(array1,array2))

#if the shape of the two array is different , then the other array will sterch it's value to calculate
#"Broadcasting" refers to the term on how Numpy handles arrays with different shapes during arithmetic operations. 
# Array of smaller size is stretched or copied across the larger array.


[10 15 20]


In [128]:
#one more example of broadcasting
students_marks = np.array([[67, 45],[90, 92],[66, 72],[32, 40]])
print(students_marks, "\n\n")

extra_marks = [5,10]
students_marks+=extra_marks
print(students_marks)


[[67 45]
 [90 92]
 [66 72]
 [32 40]] 


[[ 72  55]
 [ 95 102]
 [ 71  82]
 [ 37  50]]
