**NUMPY BASIC OPERATIONS**

In [ ]:
%%time
marks = [78, 47, 97, 55, 34]
for i in range(len(marks)):
    marks[i]+5
print(marks)

[78, 47, 97, 55, 34]
CPU times: total: 0 ns
Wall time: 988 µs


In [ ]:
%%time
item_list = ['Bread', 'Milk', 'Eggs', 'Butter', 'Cocoa']
marks = [78, 47, 96, 55, 34]
hetero_list =  [ 1,2,3.0, 'text', True, 3+2j ]


CPU times: total: 0 ns
Wall time: 0 ns


In [ ]:
%%time
#making list without numpy
list1 = list(range(1,1000000))
list2 = list(range(2,1000001))
list3 = []
for i in range(len(list1)):
    list3.append(list1[i]+list2[i])


CPU times: total: 188 ms
Wall time: 179 ms


In [ ]:
%%time
#making list using numpy - Arrange

import numpy as np
a = np.arange(1,1000000)
b = np.arange(2,1000001)
c = a+b

CPU times: total: 15.6 ms
Wall time: 6.58 ms


In [4]:
%%time
#making list using numpy
import numpy as np
a = np.arange(1,10,2)
b = np.arange(2,11,2)
print(a)
print(b)
c = a+b
print(c)

[1 3 5 7 9]
[ 2  4  6  8 10]
[ 3  7 11 15 19]
CPU times: total: 0 ns
Wall time: 879 µs


In [15]:
#LINESPACE
#Generating values between 0 and 10
arr = np.linspace(0,10)
print(arr)
print('Length of arr: ',len(arr))

#Number of values = 3
print(np.linspace(0,10,3))


[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
Length of arr:  50
[ 0.  5. 10.]


In [18]:
#Zeros

#1D
print(np.zeros(5))
#2D
print(np.zeros([2,3]))


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
#Ones

#1D
print(np.ones(5))
#2D
print(np.ones([2,3]))

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
#FULL

#number=5, value=8
import numpy as np
print(np.full(5,8))

#shape=[3,3], value=numpy
print(np.full([3,3],'numpy'))



[8 8 8 8 8]
[['numpy' 'numpy' 'numpy']
 ['numpy' 'numpy' 'numpy']
 ['numpy' 'numpy' 'numpy']]


In [23]:
#3x3 identity matrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**RANDOM CHOICES**

In [40]:
#generating 5 random numbers from a uniform distribution
np.random.rand(5)



array([9, 6, 1, 8, 6])

In [67]:
#random integer values low=1, high=10, number of values=5
print(np.random.randint(1,6, size=1))

[3]


In [79]:
#random integer values high=100, shape = (3,5)
print(np.random.randint(1,6, size=(3,5)))

[[5 1 2 3 5]
 [1 2 3 1 2]
 [1 2 5 1 2]]


In [78]:
#returns a single random value from the array
x = np.random.choice([9, 3, 7, 5])
print(x)


3


In [81]:
#returns 3*5 random values from the array
x = np.random.choice([9, 3, 7, 5], size=(3, 5))
print(x)


[[9 7 3 7 9]
 [9 7 5 3 9]
 [5 7 3 9 3]]


**CREAT ARRAY**

In [ ]:
#creating array using numpy
import numpy as np
marks_arr = np.array([1,3,4,6])
marks_arr


array([1, 3, 4, 6])

In [ ]:
#import the list in a numpy array
Numbers = [130, 165, 150, 150, 140]
numbers_array = np.array(Numbers)
numbers_array


array([130, 165, 150, 150, 140])

**2D ARRAY**

In [ ]:
onebyone = np.array([1])#1X1
print(onebyone, onebyone.shape)

onebytwo = np.array([1,2]) #1X2
print(onebytwo, onebytwo.shape)

onebythree = np.array([1,2,3]) #1X3
print(onebythree, onebythree.shape)

print("\n \n \n")


twobyone = np.array([[1], [2]]) #2X1
print(twobyone, twobyone.shape)

twobytwo = np.array([[1, 2], [3, 4]]) #2X2
print(twobytwo, twobytwo.shape)

twobythree = np.array([[1, 2, 3], [4, 5, 6]]) #2X3
print(twobythree, twobythree.shape)

print("\n \n \n")

threebyone = np.array([[1], [2], [3]]) #3X1
print(threebyone, threebyone .shape)

threeone = 
threebytwo = np.array([[1, 2], [3, 4], [5,6]]) #3X2
print(threebytwo, threebytwo.shape)

threebythree = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]]) #3X3
print(threebythree, threebythree.shape)


[1] (1,)
[1 2] (2,)
[1 2 3] (3,)

 
 

[[1]
 [2]] (2, 1)
[[1 2]
 [3 4]] (2, 2)
[[1 2 3]
 [4 5 6]] (2, 3)

 
 

[[1]
 [2]
 [3]] (3, 1)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [ ]:
import numpy as np
#making 2D array
two_dimen = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
two_dimen_array = np.array(two_dimen)
print(two_dimen_array)

#will show the shape of 2D array
print(two_dimen_array.shape)

#will show the data type of the array
print(two_dimen_array.dtype)

two_dimen_array = np.array(two_dimen, dtype = 'float') #making the array float
print(two_dimen_array)
print(two_dimen_array.dtype)

[[ 18  15  18  16  17]
 [130 165 150 150 140]
 [307 350 318 304 302]]
(3, 5)
int32
[[ 18.  15.  18.  16.  17.]
 [130. 165. 150. 150. 140.]
 [307. 350. 318. 304. 302.]]
float64


In [6]:
#Making 10X2 matrix - np.column_stack

import numpy as np
days = np.array([1,2,3,4,5,6,7,8,9,10])
steps = np.array([6012, 7079, 6886, 7230, 4598, 5564, 6971, 7763, 8032, 9569])
step_count = np.column_stack([days, steps])
print(step_count)


[[   1 6012]
 [   2 7079]
 [   3 6886]
 [   4 7230]
 [   5 4598]
 [   6 5564]
 [   7 6971]
 [   8 7763]
 [   9 8032]
 [  10 9569]]


In [ ]:
#Accessing element from 1D array.
fruits = np.array(['Strawberry', 'Mango', 'Lichi', 'Grapes', 'Watermelon'])
fruits[1]


'Mango'

In [2]:
import numpy as np
#Accessing element from 2D array.
fruits = np.array(['Strawberry', 'Mango', 'Lichi', 'Grapes', 'Watermelon'])
price = [130, 165, 150, 150, 140]

#importing two list into a 2D array
fruits_price_array = np.array([fruits, price])
print(fruits_price_array)

#accesing a row
print(fruits_price_array[0], "\n")

#accesing a single cell
print(fruits_price_array[0,1])



[['Strawberry' 'Mango' 'Lichi' 'Grapes' 'Watermelon']
 ['130' '165' '150' '150' '140']]
['Strawberry' 'Mango' 'Lichi' 'Grapes' 'Watermelon'] 

Mango


In [ ]:
#1d arrray slicing

price = [130, 165, 150, 150, 140]
print(price[1:3])

[165, 150]


In [ ]:
#2D arrray slicing
fruits = np.array(['Strawberry', 'Mango', 'Lichi', 'Grapes', 'Watermelon'])
price = [130, 165, 150, 150, 140]
numbers = [18, 15, 18, 16, 17]

fruits_price_numbers = np.array([fruits, price,numbers])
print(fruits_price_numbers, "\n \n")

print(fruits_price_numbers[1:3, 1:3]) #[row, colum]



[['Strawberry' 'Mango' 'Lichi' 'Grapes' 'Watermelon']
 ['130' '165' '150' '150' '140']
 ['18' '15' '18' '16' '17']] 
 

[['165' '150']
 ['15' '18']]


In [ ]:
#mean , median , max, min, argmin, argmax
num= np.array( [130, 165, 150, 190, 140])
print("Mean = ",np.mean(num))
print("Median = ",np.median(num))
print("Min = ",np.min(num))
print("Max = ",np.max(num))
print("Index of Minimum : ", np.argmin(num))
print("Index of Maximum : ", np.argmax(num))

Mean =  155.0
Median =  150.0
Min =  130
Max =  190
Index of Minimum :  0
Index of Maximum :  3


In [ ]:
#where - filter data
num= np.array( [130, 165, 150, 190, 140])
x = np.where(num > 130)
print(x)
num[x]

(array([1, 2, 3, 4], dtype=int64),)


array([165, 150, 190, 140])

In [ ]:
#sorting
num= np.array( [130, 165, 150, 190, 140])
print('original array: ', num)
print('Sorted array: ', np.sort(num)) #temporary sort
print('original array after sorting: ', num)
num.sort() #permanent sort
print('array.sort() :  ', num)

original array:  [130 165 150 190 140]
Sorted array:  [130 140 150 165 190]
original array after sorting:  [130 165 150 190 140]
array.sort() :   [130 140 150 165 190]


In [ ]:
#Vectorized operations

marks= np.array([78, 92, 36, 64, 89])
print(np.sum(marks)) #sum of all elements (1D array)

aditional = [2,3,4,5,6]
marks+=aditional #sum of array and list
print(marks)

marks = np.add(marks,aditional) #2D array
print(marks)



359
[80 95 40 69 95]
[ 82  98  44  74 101]


In [ ]:
#operations for 2D array

a = np.array([5,6,7,8])
b = np.array([1,2,3,4])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.negative(a))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.floor_divide(a,b))
print(np.power(a,b))
print(np.mod(a,b))



[ 6  8 10 12]
[4 4 4 4]
[-5 -6 -7 -8]
[ 5 12 21 32]
[5.         3.         2.33333333 2.        ]
[5 3 2 2]
[   5   36  343 4096]
[0 0 1 0]


In [ ]:
#Broadcasting

import numpy as np
# Array 1
array1=np.array([5, 10, 15])
# Array 2
array2=np.array([5])
print(np.add(array1,array2))

#if the shape of the two array is different , then the other array will sterch it's value to calculate
#"Broadcasting" refers to the term on how Numpy handles arrays with different shapes during arithmetic operations. 
# Array of smaller size is stretched or copied across the larger array.


[10 15 20]


In [ ]:
#one more example of broadcasting

students_marks = np.array([[67, 45],[90, 92],[66, 72],[32, 40]])
print(students_marks, "\n\n")

extra_marks = [5,10]
students_marks+=extra_marks
print(students_marks)


[[67 45]
 [90 92]
 [66 72]
 [32 40]] 


[[ 72  55]
 [ 95 102]
 [ 71  82]
 [ 37  50]]
